/*
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import upb.edu.lp.ide.contentassist.antlr.internal.InternalCocinitaParser;
import upb.edu.lp.services.CocinitaGrammarAccess;

public class CocinitaParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(CocinitaGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, CocinitaGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getTipoVariableAccess().getAlternatives(), "rule__TipoVariable__Alternatives");
			builder.put(grammarAccess.getCocinaAccess().getGroup(), "rule__Cocina__Group__0");
			builder.put(grammarAccess.getListaIngredientesAccess().getGroup(), "rule__ListaIngredientes__Group__0");
			builder.put(grammarAccess.getCocinaAccess().getNameAssignment_1(), "rule__Cocina__NameAssignment_1");
			builder.put(grammarAccess.getCocinaAccess().getIngredienteAssignment_3(), "rule__Cocina__IngredienteAssignment_3");
			builder.put(grammarAccess.getListaIngredientesAccess().getTipoAssignment_1(), "rule__ListaIngredientes__TipoAssignment_1");
			builder.put(grammarAccess.getListaIngredientesAccess().getNameAssignment_2(), "rule__ListaIngredientes__NameAssignment_2");
			builder.put(grammarAccess.getTipoVariableAccess().getINTAssignment_0(), "rule__TipoVariable__INTAssignment_0");
			builder.put(grammarAccess.getTipoVariableAccess().getStringAssignment_1(), "rule__TipoVariable__StringAssignment_1");
			builder.put(grammarAccess.getTipoVariableAccess().getDoubleAssignment_2(), "rule__TipoVariable__DoubleAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private CocinitaGrammarAccess grammarAccess;

	@Override
	protected InternalCocinitaParser createParser() {
		InternalCocinitaParser result = new InternalCocinitaParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public CocinitaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CocinitaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
