/**
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.cocinita;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see upb.edu.lp.cocinita.CocinitaFactory
 * @model kind="package"
 * @generated
 */
public interface CocinitaPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "cocinita";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.edu.upb/lp/Cocinita";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "cocinita";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CocinitaPackage eINSTANCE = upb.edu.lp.cocinita.impl.CocinitaPackageImpl.init();

  /**
   * The meta object id for the '{@link upb.edu.lp.cocinita.impl.CocinaImpl <em>Cocina</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.edu.lp.cocinita.impl.CocinaImpl
   * @see upb.edu.lp.cocinita.impl.CocinitaPackageImpl#getCocina()
   * @generated
   */
  int COCINA = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COCINA__NAME = 0;

  /**
   * The feature id for the '<em><b>Lista Ingredientes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COCINA__LISTA_INGREDIENTES = 1;

  /**
   * The number of structural features of the '<em>Cocina</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COCINA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link upb.edu.lp.cocinita.impl.IngredienteImpl <em>Ingrediente</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.edu.lp.cocinita.impl.IngredienteImpl
   * @see upb.edu.lp.cocinita.impl.CocinitaPackageImpl#getIngrediente()
   * @generated
   */
  int INGREDIENTE = 1;

  /**
   * The feature id for the '<em><b>Ascii</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENTE__ASCII = 0;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENTE__TIPO = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENTE__NAME = 2;

  /**
   * The number of structural features of the '<em>Ingrediente</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENTE_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link upb.edu.lp.cocinita.Cocina <em>Cocina</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cocina</em>'.
   * @see upb.edu.lp.cocinita.Cocina
   * @generated
   */
  EClass getCocina();

  /**
   * Returns the meta object for the attribute '{@link upb.edu.lp.cocinita.Cocina#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see upb.edu.lp.cocinita.Cocina#getName()
   * @see #getCocina()
   * @generated
   */
  EAttribute getCocina_Name();

  /**
   * Returns the meta object for the containment reference list '{@link upb.edu.lp.cocinita.Cocina#getListaIngredientes <em>Lista Ingredientes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lista Ingredientes</em>'.
   * @see upb.edu.lp.cocinita.Cocina#getListaIngredientes()
   * @see #getCocina()
   * @generated
   */
  EReference getCocina_ListaIngredientes();

  /**
   * Returns the meta object for class '{@link upb.edu.lp.cocinita.Ingrediente <em>Ingrediente</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ingrediente</em>'.
   * @see upb.edu.lp.cocinita.Ingrediente
   * @generated
   */
  EClass getIngrediente();

  /**
   * Returns the meta object for the attribute '{@link upb.edu.lp.cocinita.Ingrediente#getAscii <em>Ascii</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ascii</em>'.
   * @see upb.edu.lp.cocinita.Ingrediente#getAscii()
   * @see #getIngrediente()
   * @generated
   */
  EAttribute getIngrediente_Ascii();

  /**
   * Returns the meta object for the attribute '{@link upb.edu.lp.cocinita.Ingrediente#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo</em>'.
   * @see upb.edu.lp.cocinita.Ingrediente#getTipo()
   * @see #getIngrediente()
   * @generated
   */
  EAttribute getIngrediente_Tipo();

  /**
   * Returns the meta object for the attribute '{@link upb.edu.lp.cocinita.Ingrediente#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see upb.edu.lp.cocinita.Ingrediente#getName()
   * @see #getIngrediente()
   * @generated
   */
  EAttribute getIngrediente_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CocinitaFactory getCocinitaFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link upb.edu.lp.cocinita.impl.CocinaImpl <em>Cocina</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.edu.lp.cocinita.impl.CocinaImpl
     * @see upb.edu.lp.cocinita.impl.CocinitaPackageImpl#getCocina()
     * @generated
     */
    EClass COCINA = eINSTANCE.getCocina();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COCINA__NAME = eINSTANCE.getCocina_Name();

    /**
     * The meta object literal for the '<em><b>Lista Ingredientes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COCINA__LISTA_INGREDIENTES = eINSTANCE.getCocina_ListaIngredientes();

    /**
     * The meta object literal for the '{@link upb.edu.lp.cocinita.impl.IngredienteImpl <em>Ingrediente</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.edu.lp.cocinita.impl.IngredienteImpl
     * @see upb.edu.lp.cocinita.impl.CocinitaPackageImpl#getIngrediente()
     * @generated
     */
    EClass INGREDIENTE = eINSTANCE.getIngrediente();

    /**
     * The meta object literal for the '<em><b>Ascii</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGREDIENTE__ASCII = eINSTANCE.getIngrediente_Ascii();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGREDIENTE__TIPO = eINSTANCE.getIngrediente_Tipo();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGREDIENTE__NAME = eINSTANCE.getIngrediente_Name();

  }

} //CocinitaPackage
