/**
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.cocinita;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see upb.edu.lp.cocinita.CocinitaFactory
 * @model kind="package"
 * @generated
 */
public interface CocinitaPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "cocinita";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.edu.upb/lp/Cocinita";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "cocinita";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CocinitaPackage eINSTANCE = upb.edu.lp.cocinita.impl.CocinitaPackageImpl.init();

  /**
   * The meta object id for the '{@link upb.edu.lp.cocinita.impl.CocinaImpl <em>Cocina</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.edu.lp.cocinita.impl.CocinaImpl
   * @see upb.edu.lp.cocinita.impl.CocinitaPackageImpl#getCocina()
   * @generated
   */
  int COCINA = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COCINA__NAME = 0;

  /**
   * The feature id for the '<em><b>Ingrediente</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COCINA__INGREDIENTE = 1;

  /**
   * The number of structural features of the '<em>Cocina</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COCINA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link upb.edu.lp.cocinita.impl.ListaIngredientesImpl <em>Lista Ingredientes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.edu.lp.cocinita.impl.ListaIngredientesImpl
   * @see upb.edu.lp.cocinita.impl.CocinitaPackageImpl#getListaIngredientes()
   * @generated
   */
  int LISTA_INGREDIENTES = 1;

  /**
   * The feature id for the '<em><b>Ascii</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTA_INGREDIENTES__ASCII = 0;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTA_INGREDIENTES__TIPO = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTA_INGREDIENTES__NAME = 2;

  /**
   * The number of structural features of the '<em>Lista Ingredientes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTA_INGREDIENTES_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link upb.edu.lp.cocinita.impl.TipoVariableImpl <em>Tipo Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.edu.lp.cocinita.impl.TipoVariableImpl
   * @see upb.edu.lp.cocinita.impl.CocinitaPackageImpl#getTipoVariable()
   * @generated
   */
  int TIPO_VARIABLE = 2;

  /**
   * The feature id for the '<em><b>INT</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO_VARIABLE__INT = 0;

  /**
   * The feature id for the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO_VARIABLE__STRING = 1;

  /**
   * The number of structural features of the '<em>Tipo Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO_VARIABLE_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link upb.edu.lp.cocinita.Cocina <em>Cocina</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cocina</em>'.
   * @see upb.edu.lp.cocinita.Cocina
   * @generated
   */
  EClass getCocina();

  /**
   * Returns the meta object for the attribute '{@link upb.edu.lp.cocinita.Cocina#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see upb.edu.lp.cocinita.Cocina#getName()
   * @see #getCocina()
   * @generated
   */
  EAttribute getCocina_Name();

  /**
   * Returns the meta object for the containment reference list '{@link upb.edu.lp.cocinita.Cocina#getIngrediente <em>Ingrediente</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ingrediente</em>'.
   * @see upb.edu.lp.cocinita.Cocina#getIngrediente()
   * @see #getCocina()
   * @generated
   */
  EReference getCocina_Ingrediente();

  /**
   * Returns the meta object for class '{@link upb.edu.lp.cocinita.ListaIngredientes <em>Lista Ingredientes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lista Ingredientes</em>'.
   * @see upb.edu.lp.cocinita.ListaIngredientes
   * @generated
   */
  EClass getListaIngredientes();

  /**
   * Returns the meta object for the attribute '{@link upb.edu.lp.cocinita.ListaIngredientes#getAscii <em>Ascii</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ascii</em>'.
   * @see upb.edu.lp.cocinita.ListaIngredientes#getAscii()
   * @see #getListaIngredientes()
   * @generated
   */
  EAttribute getListaIngredientes_Ascii();

  /**
   * Returns the meta object for the containment reference '{@link upb.edu.lp.cocinita.ListaIngredientes#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tipo</em>'.
   * @see upb.edu.lp.cocinita.ListaIngredientes#getTipo()
   * @see #getListaIngredientes()
   * @generated
   */
  EReference getListaIngredientes_Tipo();

  /**
   * Returns the meta object for the attribute '{@link upb.edu.lp.cocinita.ListaIngredientes#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see upb.edu.lp.cocinita.ListaIngredientes#getName()
   * @see #getListaIngredientes()
   * @generated
   */
  EAttribute getListaIngredientes_Name();

  /**
   * Returns the meta object for class '{@link upb.edu.lp.cocinita.TipoVariable <em>Tipo Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tipo Variable</em>'.
   * @see upb.edu.lp.cocinita.TipoVariable
   * @generated
   */
  EClass getTipoVariable();

  /**
   * Returns the meta object for the attribute '{@link upb.edu.lp.cocinita.TipoVariable#getINT <em>INT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>INT</em>'.
   * @see upb.edu.lp.cocinita.TipoVariable#getINT()
   * @see #getTipoVariable()
   * @generated
   */
  EAttribute getTipoVariable_INT();

  /**
   * Returns the meta object for the attribute '{@link upb.edu.lp.cocinita.TipoVariable#getString <em>String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String</em>'.
   * @see upb.edu.lp.cocinita.TipoVariable#getString()
   * @see #getTipoVariable()
   * @generated
   */
  EAttribute getTipoVariable_String();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CocinitaFactory getCocinitaFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link upb.edu.lp.cocinita.impl.CocinaImpl <em>Cocina</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.edu.lp.cocinita.impl.CocinaImpl
     * @see upb.edu.lp.cocinita.impl.CocinitaPackageImpl#getCocina()
     * @generated
     */
    EClass COCINA = eINSTANCE.getCocina();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COCINA__NAME = eINSTANCE.getCocina_Name();

    /**
     * The meta object literal for the '<em><b>Ingrediente</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COCINA__INGREDIENTE = eINSTANCE.getCocina_Ingrediente();

    /**
     * The meta object literal for the '{@link upb.edu.lp.cocinita.impl.ListaIngredientesImpl <em>Lista Ingredientes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.edu.lp.cocinita.impl.ListaIngredientesImpl
     * @see upb.edu.lp.cocinita.impl.CocinitaPackageImpl#getListaIngredientes()
     * @generated
     */
    EClass LISTA_INGREDIENTES = eINSTANCE.getListaIngredientes();

    /**
     * The meta object literal for the '<em><b>Ascii</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LISTA_INGREDIENTES__ASCII = eINSTANCE.getListaIngredientes_Ascii();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LISTA_INGREDIENTES__TIPO = eINSTANCE.getListaIngredientes_Tipo();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LISTA_INGREDIENTES__NAME = eINSTANCE.getListaIngredientes_Name();

    /**
     * The meta object literal for the '{@link upb.edu.lp.cocinita.impl.TipoVariableImpl <em>Tipo Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.edu.lp.cocinita.impl.TipoVariableImpl
     * @see upb.edu.lp.cocinita.impl.CocinitaPackageImpl#getTipoVariable()
     * @generated
     */
    EClass TIPO_VARIABLE = eINSTANCE.getTipoVariable();

    /**
     * The meta object literal for the '<em><b>INT</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIPO_VARIABLE__INT = eINSTANCE.getTipoVariable_INT();

    /**
     * The meta object literal for the '<em><b>String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIPO_VARIABLE__STRING = eINSTANCE.getTipoVariable_String();

  }

} //CocinitaPackage
