/**
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.cocinita;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cocina</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link upb.edu.lp.cocinita.Cocina#getName <em>Name</em>}</li>
 *   <li>{@link upb.edu.lp.cocinita.Cocina#getListaIngredientes <em>Lista Ingredientes</em>}</li>
 *   <li>{@link upb.edu.lp.cocinita.Cocina#getNBowl <em>NBowl</em>}</li>
 *   <li>{@link upb.edu.lp.cocinita.Cocina#getListaInstrucciones <em>Lista Instrucciones</em>}</li>
 *   <li>{@link upb.edu.lp.cocinita.Cocina#getBowl <em>Bowl</em>}</li>
 * </ul>
 *
 * @see upb.edu.lp.cocinita.CocinitaPackage#getCocina()
 * @model
 * @generated
 */
public interface Cocina extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see upb.edu.lp.cocinita.CocinitaPackage#getCocina_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link upb.edu.lp.cocinita.Cocina#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Lista Ingredientes</b></em>' containment reference list.
   * The list contents are of type {@link upb.edu.lp.cocinita.Ingrediente}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lista Ingredientes</em>' containment reference list.
   * @see upb.edu.lp.cocinita.CocinitaPackage#getCocina_ListaIngredientes()
   * @model containment="true"
   * @generated
   */
  EList<Ingrediente> getListaIngredientes();

  /**
   * Returns the value of the '<em><b>NBowl</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>NBowl</em>' attribute.
   * @see #setNBowl(int)
   * @see upb.edu.lp.cocinita.CocinitaPackage#getCocina_NBowl()
   * @model
   * @generated
   */
  int getNBowl();

  /**
   * Sets the value of the '{@link upb.edu.lp.cocinita.Cocina#getNBowl <em>NBowl</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>NBowl</em>' attribute.
   * @see #getNBowl()
   * @generated
   */
  void setNBowl(int value);

  /**
   * Returns the value of the '<em><b>Lista Instrucciones</b></em>' containment reference list.
   * The list contents are of type {@link upb.edu.lp.cocinita.Instruccion}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lista Instrucciones</em>' containment reference list.
   * @see upb.edu.lp.cocinita.CocinitaPackage#getCocina_ListaInstrucciones()
   * @model containment="true"
   * @generated
   */
  EList<Instruccion> getListaInstrucciones();

  /**
   * Returns the value of the '<em><b>Bowl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bowl</em>' containment reference.
   * @see #setBowl(Bowl)
   * @see upb.edu.lp.cocinita.CocinitaPackage#getCocina_Bowl()
   * @model containment="true"
   * @generated
   */
  Bowl getBowl();

  /**
   * Sets the value of the '{@link upb.edu.lp.cocinita.Cocina#getBowl <em>Bowl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bowl</em>' containment reference.
   * @see #getBowl()
   * @generated
   */
  void setBowl(Bowl value);

} // Cocina
