/**
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.cocinita;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see upb.edu.lp.cocinita.CocinitaPackage
 * @generated
 */
public interface CocinitaFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CocinitaFactory eINSTANCE = upb.edu.lp.cocinita.impl.CocinitaFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Cocina</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Cocina</em>'.
   * @generated
   */
  Cocina createCocina();

  /**
   * Returns a new object of class '<em>Ingrediente</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ingrediente</em>'.
   * @generated
   */
  Ingrediente createIngrediente();

  /**
   * Returns a new object of class '<em>Bowl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bowl</em>'.
   * @generated
   */
  Bowl createBowl();

  /**
   * Returns a new object of class '<em>Instruccion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Instruccion</em>'.
   * @generated
   */
  Instruccion createInstruccion();

  /**
   * Returns a new object of class '<em>Expresion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expresion</em>'.
   * @generated
   */
  Expresion createExpresion();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  CocinitaPackage getCocinitaPackage();

} //CocinitaFactory
