/**
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.cocinita;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see upb.edu.lp.cocinita.CocinitaFactory
 * @model kind="package"
 * @generated
 */
public interface CocinitaPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "cocinita";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.edu.upb/lp/Cocinita";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "cocinita";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CocinitaPackage eINSTANCE = upb.edu.lp.cocinita.impl.CocinitaPackageImpl.init();

  /**
   * The meta object id for the '{@link upb.edu.lp.cocinita.impl.CocinaImpl <em>Cocina</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.edu.lp.cocinita.impl.CocinaImpl
   * @see upb.edu.lp.cocinita.impl.CocinitaPackageImpl#getCocina()
   * @generated
   */
  int COCINA = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COCINA__NAME = 0;

  /**
   * The feature id for the '<em><b>Lista Ingredientes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COCINA__LISTA_INGREDIENTES = 1;

  /**
   * The feature id for the '<em><b>NBowl</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COCINA__NBOWL = 2;

  /**
   * The feature id for the '<em><b>Lista Instrucciones</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COCINA__LISTA_INSTRUCCIONES = 3;

  /**
   * The feature id for the '<em><b>Bowl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COCINA__BOWL = 4;

  /**
   * The number of structural features of the '<em>Cocina</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COCINA_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link upb.edu.lp.cocinita.impl.IngredienteImpl <em>Ingrediente</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.edu.lp.cocinita.impl.IngredienteImpl
   * @see upb.edu.lp.cocinita.impl.CocinitaPackageImpl#getIngrediente()
   * @generated
   */
  int INGREDIENTE = 1;

  /**
   * The feature id for the '<em><b>Ascii</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENTE__ASCII = 0;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENTE__TIPO = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENTE__NAME = 2;

  /**
   * The number of structural features of the '<em>Ingrediente</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENTE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link upb.edu.lp.cocinita.impl.BowlImpl <em>Bowl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.edu.lp.cocinita.impl.BowlImpl
   * @see upb.edu.lp.cocinita.impl.CocinitaPackageImpl#getBowl()
   * @generated
   */
  int BOWL = 2;

  /**
   * The feature id for the '<em><b>Numero</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOWL__NUMERO = 0;

  /**
   * The number of structural features of the '<em>Bowl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOWL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link upb.edu.lp.cocinita.impl.InstruccionImpl <em>Instruccion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.edu.lp.cocinita.impl.InstruccionImpl
   * @see upb.edu.lp.cocinita.impl.CocinitaPackageImpl#getInstruccion()
   * @generated
   */
  int INSTRUCCION = 3;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCCION__EXP = 0;

  /**
   * The feature id for the '<em><b>Bowl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCCION__BOWL = 1;

  /**
   * The feature id for the '<em><b>Ingrediente</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCCION__INGREDIENTE = 2;

  /**
   * The number of structural features of the '<em>Instruccion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCCION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link upb.edu.lp.cocinita.impl.ExpresionImpl <em>Expresion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.edu.lp.cocinita.impl.ExpresionImpl
   * @see upb.edu.lp.cocinita.impl.CocinitaPackageImpl#getExpresion()
   * @generated
   */
  int EXPRESION = 4;

  /**
   * The feature id for the '<em><b>Ingrediente</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESION__INGREDIENTE = 0;

  /**
   * The feature id for the '<em><b>Bowl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESION__BOWL = 1;

  /**
   * The number of structural features of the '<em>Expresion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESION_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link upb.edu.lp.cocinita.Cocina <em>Cocina</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cocina</em>'.
   * @see upb.edu.lp.cocinita.Cocina
   * @generated
   */
  EClass getCocina();

  /**
   * Returns the meta object for the attribute '{@link upb.edu.lp.cocinita.Cocina#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see upb.edu.lp.cocinita.Cocina#getName()
   * @see #getCocina()
   * @generated
   */
  EAttribute getCocina_Name();

  /**
   * Returns the meta object for the containment reference list '{@link upb.edu.lp.cocinita.Cocina#getListaIngredientes <em>Lista Ingredientes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lista Ingredientes</em>'.
   * @see upb.edu.lp.cocinita.Cocina#getListaIngredientes()
   * @see #getCocina()
   * @generated
   */
  EReference getCocina_ListaIngredientes();

  /**
   * Returns the meta object for the attribute '{@link upb.edu.lp.cocinita.Cocina#getNBowl <em>NBowl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>NBowl</em>'.
   * @see upb.edu.lp.cocinita.Cocina#getNBowl()
   * @see #getCocina()
   * @generated
   */
  EAttribute getCocina_NBowl();

  /**
   * Returns the meta object for the containment reference list '{@link upb.edu.lp.cocinita.Cocina#getListaInstrucciones <em>Lista Instrucciones</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lista Instrucciones</em>'.
   * @see upb.edu.lp.cocinita.Cocina#getListaInstrucciones()
   * @see #getCocina()
   * @generated
   */
  EReference getCocina_ListaInstrucciones();

  /**
   * Returns the meta object for the containment reference '{@link upb.edu.lp.cocinita.Cocina#getBowl <em>Bowl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bowl</em>'.
   * @see upb.edu.lp.cocinita.Cocina#getBowl()
   * @see #getCocina()
   * @generated
   */
  EReference getCocina_Bowl();

  /**
   * Returns the meta object for class '{@link upb.edu.lp.cocinita.Ingrediente <em>Ingrediente</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ingrediente</em>'.
   * @see upb.edu.lp.cocinita.Ingrediente
   * @generated
   */
  EClass getIngrediente();

  /**
   * Returns the meta object for the attribute '{@link upb.edu.lp.cocinita.Ingrediente#getAscii <em>Ascii</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ascii</em>'.
   * @see upb.edu.lp.cocinita.Ingrediente#getAscii()
   * @see #getIngrediente()
   * @generated
   */
  EAttribute getIngrediente_Ascii();

  /**
   * Returns the meta object for the attribute '{@link upb.edu.lp.cocinita.Ingrediente#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo</em>'.
   * @see upb.edu.lp.cocinita.Ingrediente#getTipo()
   * @see #getIngrediente()
   * @generated
   */
  EAttribute getIngrediente_Tipo();

  /**
   * Returns the meta object for the attribute '{@link upb.edu.lp.cocinita.Ingrediente#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see upb.edu.lp.cocinita.Ingrediente#getName()
   * @see #getIngrediente()
   * @generated
   */
  EAttribute getIngrediente_Name();

  /**
   * Returns the meta object for class '{@link upb.edu.lp.cocinita.Bowl <em>Bowl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bowl</em>'.
   * @see upb.edu.lp.cocinita.Bowl
   * @generated
   */
  EClass getBowl();

  /**
   * Returns the meta object for the attribute '{@link upb.edu.lp.cocinita.Bowl#getNumero <em>Numero</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Numero</em>'.
   * @see upb.edu.lp.cocinita.Bowl#getNumero()
   * @see #getBowl()
   * @generated
   */
  EAttribute getBowl_Numero();

  /**
   * Returns the meta object for class '{@link upb.edu.lp.cocinita.Instruccion <em>Instruccion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruccion</em>'.
   * @see upb.edu.lp.cocinita.Instruccion
   * @generated
   */
  EClass getInstruccion();

  /**
   * Returns the meta object for the containment reference '{@link upb.edu.lp.cocinita.Instruccion#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see upb.edu.lp.cocinita.Instruccion#getExp()
   * @see #getInstruccion()
   * @generated
   */
  EReference getInstruccion_Exp();

  /**
   * Returns the meta object for the containment reference '{@link upb.edu.lp.cocinita.Instruccion#getBowl <em>Bowl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bowl</em>'.
   * @see upb.edu.lp.cocinita.Instruccion#getBowl()
   * @see #getInstruccion()
   * @generated
   */
  EReference getInstruccion_Bowl();

  /**
   * Returns the meta object for the reference '{@link upb.edu.lp.cocinita.Instruccion#getIngrediente <em>Ingrediente</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ingrediente</em>'.
   * @see upb.edu.lp.cocinita.Instruccion#getIngrediente()
   * @see #getInstruccion()
   * @generated
   */
  EReference getInstruccion_Ingrediente();

  /**
   * Returns the meta object for class '{@link upb.edu.lp.cocinita.Expresion <em>Expresion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expresion</em>'.
   * @see upb.edu.lp.cocinita.Expresion
   * @generated
   */
  EClass getExpresion();

  /**
   * Returns the meta object for the reference '{@link upb.edu.lp.cocinita.Expresion#getIngrediente <em>Ingrediente</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ingrediente</em>'.
   * @see upb.edu.lp.cocinita.Expresion#getIngrediente()
   * @see #getExpresion()
   * @generated
   */
  EReference getExpresion_Ingrediente();

  /**
   * Returns the meta object for the containment reference '{@link upb.edu.lp.cocinita.Expresion#getBowl <em>Bowl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bowl</em>'.
   * @see upb.edu.lp.cocinita.Expresion#getBowl()
   * @see #getExpresion()
   * @generated
   */
  EReference getExpresion_Bowl();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CocinitaFactory getCocinitaFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link upb.edu.lp.cocinita.impl.CocinaImpl <em>Cocina</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.edu.lp.cocinita.impl.CocinaImpl
     * @see upb.edu.lp.cocinita.impl.CocinitaPackageImpl#getCocina()
     * @generated
     */
    EClass COCINA = eINSTANCE.getCocina();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COCINA__NAME = eINSTANCE.getCocina_Name();

    /**
     * The meta object literal for the '<em><b>Lista Ingredientes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COCINA__LISTA_INGREDIENTES = eINSTANCE.getCocina_ListaIngredientes();

    /**
     * The meta object literal for the '<em><b>NBowl</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COCINA__NBOWL = eINSTANCE.getCocina_NBowl();

    /**
     * The meta object literal for the '<em><b>Lista Instrucciones</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COCINA__LISTA_INSTRUCCIONES = eINSTANCE.getCocina_ListaInstrucciones();

    /**
     * The meta object literal for the '<em><b>Bowl</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COCINA__BOWL = eINSTANCE.getCocina_Bowl();

    /**
     * The meta object literal for the '{@link upb.edu.lp.cocinita.impl.IngredienteImpl <em>Ingrediente</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.edu.lp.cocinita.impl.IngredienteImpl
     * @see upb.edu.lp.cocinita.impl.CocinitaPackageImpl#getIngrediente()
     * @generated
     */
    EClass INGREDIENTE = eINSTANCE.getIngrediente();

    /**
     * The meta object literal for the '<em><b>Ascii</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGREDIENTE__ASCII = eINSTANCE.getIngrediente_Ascii();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGREDIENTE__TIPO = eINSTANCE.getIngrediente_Tipo();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGREDIENTE__NAME = eINSTANCE.getIngrediente_Name();

    /**
     * The meta object literal for the '{@link upb.edu.lp.cocinita.impl.BowlImpl <em>Bowl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.edu.lp.cocinita.impl.BowlImpl
     * @see upb.edu.lp.cocinita.impl.CocinitaPackageImpl#getBowl()
     * @generated
     */
    EClass BOWL = eINSTANCE.getBowl();

    /**
     * The meta object literal for the '<em><b>Numero</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOWL__NUMERO = eINSTANCE.getBowl_Numero();

    /**
     * The meta object literal for the '{@link upb.edu.lp.cocinita.impl.InstruccionImpl <em>Instruccion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.edu.lp.cocinita.impl.InstruccionImpl
     * @see upb.edu.lp.cocinita.impl.CocinitaPackageImpl#getInstruccion()
     * @generated
     */
    EClass INSTRUCCION = eINSTANCE.getInstruccion();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCCION__EXP = eINSTANCE.getInstruccion_Exp();

    /**
     * The meta object literal for the '<em><b>Bowl</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCCION__BOWL = eINSTANCE.getInstruccion_Bowl();

    /**
     * The meta object literal for the '<em><b>Ingrediente</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCCION__INGREDIENTE = eINSTANCE.getInstruccion_Ingrediente();

    /**
     * The meta object literal for the '{@link upb.edu.lp.cocinita.impl.ExpresionImpl <em>Expresion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.edu.lp.cocinita.impl.ExpresionImpl
     * @see upb.edu.lp.cocinita.impl.CocinitaPackageImpl#getExpresion()
     * @generated
     */
    EClass EXPRESION = eINSTANCE.getExpresion();

    /**
     * The meta object literal for the '<em><b>Ingrediente</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESION__INGREDIENTE = eINSTANCE.getExpresion_Ingrediente();

    /**
     * The meta object literal for the '<em><b>Bowl</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESION__BOWL = eINSTANCE.getExpresion_Bowl();

  }

} //CocinitaPackage
