/**
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.cocinita;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lista Ingredientes</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link upb.edu.lp.cocinita.ListaIngredientes#getAscii <em>Ascii</em>}</li>
 *   <li>{@link upb.edu.lp.cocinita.ListaIngredientes#getTipo <em>Tipo</em>}</li>
 *   <li>{@link upb.edu.lp.cocinita.ListaIngredientes#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see upb.edu.lp.cocinita.CocinitaPackage#getListaIngredientes()
 * @model
 * @generated
 */
public interface ListaIngredientes extends EObject
{
  /**
   * Returns the value of the '<em><b>Ascii</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ascii</em>' attribute.
   * @see #setAscii(String)
   * @see upb.edu.lp.cocinita.CocinitaPackage#getListaIngredientes_Ascii()
   * @model
   * @generated
   */
  String getAscii();

  /**
   * Sets the value of the '{@link upb.edu.lp.cocinita.ListaIngredientes#getAscii <em>Ascii</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ascii</em>' attribute.
   * @see #getAscii()
   * @generated
   */
  void setAscii(String value);

  /**
   * Returns the value of the '<em><b>Tipo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo</em>' containment reference.
   * @see #setTipo(TipoVariable)
   * @see upb.edu.lp.cocinita.CocinitaPackage#getListaIngredientes_Tipo()
   * @model containment="true"
   * @generated
   */
  TipoVariable getTipo();

  /**
   * Sets the value of the '{@link upb.edu.lp.cocinita.ListaIngredientes#getTipo <em>Tipo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo</em>' containment reference.
   * @see #getTipo()
   * @generated
   */
  void setTipo(TipoVariable value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see upb.edu.lp.cocinita.CocinitaPackage#getListaIngredientes_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link upb.edu.lp.cocinita.ListaIngredientes#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // ListaIngredientes
