/**
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.cocinita;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tipo Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link upb.edu.lp.cocinita.TipoVariable#getINT <em>INT</em>}</li>
 *   <li>{@link upb.edu.lp.cocinita.TipoVariable#getString <em>String</em>}</li>
 *   <li>{@link upb.edu.lp.cocinita.TipoVariable#getDouble <em>Double</em>}</li>
 * </ul>
 *
 * @see upb.edu.lp.cocinita.CocinitaPackage#getTipoVariable()
 * @model
 * @generated
 */
public interface TipoVariable extends EObject
{
  /**
   * Returns the value of the '<em><b>INT</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>INT</em>' attribute.
   * @see #setINT(String)
   * @see upb.edu.lp.cocinita.CocinitaPackage#getTipoVariable_INT()
   * @model
   * @generated
   */
  String getINT();

  /**
   * Sets the value of the '{@link upb.edu.lp.cocinita.TipoVariable#getINT <em>INT</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>INT</em>' attribute.
   * @see #getINT()
   * @generated
   */
  void setINT(String value);

  /**
   * Returns the value of the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>String</em>' attribute.
   * @see #setString(String)
   * @see upb.edu.lp.cocinita.CocinitaPackage#getTipoVariable_String()
   * @model
   * @generated
   */
  String getString();

  /**
   * Sets the value of the '{@link upb.edu.lp.cocinita.TipoVariable#getString <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String</em>' attribute.
   * @see #getString()
   * @generated
   */
  void setString(String value);

  /**
   * Returns the value of the '<em><b>Double</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Double</em>' attribute.
   * @see #setDouble(String)
   * @see upb.edu.lp.cocinita.CocinitaPackage#getTipoVariable_Double()
   * @model
   * @generated
   */
  String getDouble();

  /**
   * Sets the value of the '{@link upb.edu.lp.cocinita.TipoVariable#getDouble <em>Double</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Double</em>' attribute.
   * @see #getDouble()
   * @generated
   */
  void setDouble(String value);

} // TipoVariable
