/*
 * generated by Xtext 2.35.0
 */
package upb.edu.lp;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CocinitaStandaloneSetup extends CocinitaStandaloneSetupGenerated {

	public static void doSetup() {
		new CocinitaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
