/*
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import upb.edu.lp.parser.antlr.internal.InternalMiniLengComParser;
import upb.edu.lp.services.MiniLengComGrammarAccess;

public class MiniLengComParser extends AbstractAntlrParser {

	@Inject
	private MiniLengComGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMiniLengComParser createParser(XtextTokenStream stream) {
		return new InternalMiniLengComParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MiniLengComGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MiniLengComGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
