/*
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CocinitaUiModule extends AbstractCocinitaUiModule {

	public CocinitaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
