/*
 * generated by Xtext 2.35.0
 */
package upb.edu.lp;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MiniLengComStandaloneSetup extends MiniLengComStandaloneSetupGenerated {

	public static void doSetup() {
		new MiniLengComStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
