/*
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.ui;

import com.google.inject.Injector;
import miniLengCom.ui.internal.MiniLengComActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MiniLengComExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MiniLengComActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MiniLengComActivator activator = MiniLengComActivator.getInstance();
		return activator != null ? activator.getInjector(MiniLengComActivator.UPB_EDU_LP_MINILENGCOM) : null;
	}

}
