/*
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import upb.edu.lp.MiniLengComRuntimeModule;
import upb.edu.lp.MiniLengComStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MiniLengComIdeSetup extends MiniLengComStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MiniLengComRuntimeModule(), new MiniLengComIdeModule()));
	}
	
}
