/**
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.cocinita.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import upb.edu.lp.cocinita.Bowl;
import upb.edu.lp.cocinita.Cocina;
import upb.edu.lp.cocinita.CocinitaPackage;
import upb.edu.lp.cocinita.Ingrediente;
import upb.edu.lp.cocinita.Instruccion;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Cocina</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link upb.edu.lp.cocinita.impl.CocinaImpl#getName <em>Name</em>}</li>
 *   <li>{@link upb.edu.lp.cocinita.impl.CocinaImpl#getListaIngredientes <em>Lista Ingredientes</em>}</li>
 *   <li>{@link upb.edu.lp.cocinita.impl.CocinaImpl#getNBowl <em>NBowl</em>}</li>
 *   <li>{@link upb.edu.lp.cocinita.impl.CocinaImpl#getListaInstrucciones <em>Lista Instrucciones</em>}</li>
 *   <li>{@link upb.edu.lp.cocinita.impl.CocinaImpl#getBowl <em>Bowl</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CocinaImpl extends MinimalEObjectImpl.Container implements Cocina
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getListaIngredientes() <em>Lista Ingredientes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getListaIngredientes()
   * @generated
   * @ordered
   */
  protected EList<Ingrediente> listaIngredientes;

  /**
   * The default value of the '{@link #getNBowl() <em>NBowl</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNBowl()
   * @generated
   * @ordered
   */
  protected static final int NBOWL_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getNBowl() <em>NBowl</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNBowl()
   * @generated
   * @ordered
   */
  protected int nBowl = NBOWL_EDEFAULT;

  /**
   * The cached value of the '{@link #getListaInstrucciones() <em>Lista Instrucciones</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getListaInstrucciones()
   * @generated
   * @ordered
   */
  protected EList<Instruccion> listaInstrucciones;

  /**
   * The cached value of the '{@link #getBowl() <em>Bowl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBowl()
   * @generated
   * @ordered
   */
  protected Bowl bowl;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CocinaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CocinitaPackage.Literals.COCINA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CocinitaPackage.COCINA__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Ingrediente> getListaIngredientes()
  {
    if (listaIngredientes == null)
    {
      listaIngredientes = new EObjectContainmentEList<Ingrediente>(Ingrediente.class, this, CocinitaPackage.COCINA__LISTA_INGREDIENTES);
    }
    return listaIngredientes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getNBowl()
  {
    return nBowl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNBowl(int newNBowl)
  {
    int oldNBowl = nBowl;
    nBowl = newNBowl;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CocinitaPackage.COCINA__NBOWL, oldNBowl, nBowl));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Instruccion> getListaInstrucciones()
  {
    if (listaInstrucciones == null)
    {
      listaInstrucciones = new EObjectContainmentEList<Instruccion>(Instruccion.class, this, CocinitaPackage.COCINA__LISTA_INSTRUCCIONES);
    }
    return listaInstrucciones;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Bowl getBowl()
  {
    return bowl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetBowl(Bowl newBowl, NotificationChain msgs)
  {
    Bowl oldBowl = bowl;
    bowl = newBowl;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CocinitaPackage.COCINA__BOWL, oldBowl, newBowl);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBowl(Bowl newBowl)
  {
    if (newBowl != bowl)
    {
      NotificationChain msgs = null;
      if (bowl != null)
        msgs = ((InternalEObject)bowl).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CocinitaPackage.COCINA__BOWL, null, msgs);
      if (newBowl != null)
        msgs = ((InternalEObject)newBowl).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CocinitaPackage.COCINA__BOWL, null, msgs);
      msgs = basicSetBowl(newBowl, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CocinitaPackage.COCINA__BOWL, newBowl, newBowl));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CocinitaPackage.COCINA__LISTA_INGREDIENTES:
        return ((InternalEList<?>)getListaIngredientes()).basicRemove(otherEnd, msgs);
      case CocinitaPackage.COCINA__LISTA_INSTRUCCIONES:
        return ((InternalEList<?>)getListaInstrucciones()).basicRemove(otherEnd, msgs);
      case CocinitaPackage.COCINA__BOWL:
        return basicSetBowl(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CocinitaPackage.COCINA__NAME:
        return getName();
      case CocinitaPackage.COCINA__LISTA_INGREDIENTES:
        return getListaIngredientes();
      case CocinitaPackage.COCINA__NBOWL:
        return getNBowl();
      case CocinitaPackage.COCINA__LISTA_INSTRUCCIONES:
        return getListaInstrucciones();
      case CocinitaPackage.COCINA__BOWL:
        return getBowl();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CocinitaPackage.COCINA__NAME:
        setName((String)newValue);
        return;
      case CocinitaPackage.COCINA__LISTA_INGREDIENTES:
        getListaIngredientes().clear();
        getListaIngredientes().addAll((Collection<? extends Ingrediente>)newValue);
        return;
      case CocinitaPackage.COCINA__NBOWL:
        setNBowl((Integer)newValue);
        return;
      case CocinitaPackage.COCINA__LISTA_INSTRUCCIONES:
        getListaInstrucciones().clear();
        getListaInstrucciones().addAll((Collection<? extends Instruccion>)newValue);
        return;
      case CocinitaPackage.COCINA__BOWL:
        setBowl((Bowl)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CocinitaPackage.COCINA__NAME:
        setName(NAME_EDEFAULT);
        return;
      case CocinitaPackage.COCINA__LISTA_INGREDIENTES:
        getListaIngredientes().clear();
        return;
      case CocinitaPackage.COCINA__NBOWL:
        setNBowl(NBOWL_EDEFAULT);
        return;
      case CocinitaPackage.COCINA__LISTA_INSTRUCCIONES:
        getListaInstrucciones().clear();
        return;
      case CocinitaPackage.COCINA__BOWL:
        setBowl((Bowl)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CocinitaPackage.COCINA__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case CocinitaPackage.COCINA__LISTA_INGREDIENTES:
        return listaIngredientes != null && !listaIngredientes.isEmpty();
      case CocinitaPackage.COCINA__NBOWL:
        return nBowl != NBOWL_EDEFAULT;
      case CocinitaPackage.COCINA__LISTA_INSTRUCCIONES:
        return listaInstrucciones != null && !listaInstrucciones.isEmpty();
      case CocinitaPackage.COCINA__BOWL:
        return bowl != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", nBowl: ");
    result.append(nBowl);
    result.append(')');
    return result.toString();
  }

} //CocinaImpl
