/**
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.cocinita.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import upb.edu.lp.cocinita.Cocina;
import upb.edu.lp.cocinita.CocinitaFactory;
import upb.edu.lp.cocinita.CocinitaPackage;
import upb.edu.lp.cocinita.ListaIngredientes;
import upb.edu.lp.cocinita.TipoVariable;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class CocinitaPackageImpl extends EPackageImpl implements CocinitaPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass cocinaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass listaIngredientesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass tipoVariableEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see upb.edu.lp.cocinita.CocinitaPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private CocinitaPackageImpl()
  {
    super(eNS_URI, CocinitaFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link CocinitaPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static CocinitaPackage init()
  {
    if (isInited) return (CocinitaPackage)EPackage.Registry.INSTANCE.getEPackage(CocinitaPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredCocinitaPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    CocinitaPackageImpl theCocinitaPackage = registeredCocinitaPackage instanceof CocinitaPackageImpl ? (CocinitaPackageImpl)registeredCocinitaPackage : new CocinitaPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theCocinitaPackage.createPackageContents();

    // Initialize created meta-data
    theCocinitaPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theCocinitaPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(CocinitaPackage.eNS_URI, theCocinitaPackage);
    return theCocinitaPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCocina()
  {
    return cocinaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCocina_Name()
  {
    return (EAttribute)cocinaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCocina_Ingrediente()
  {
    return (EReference)cocinaEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getListaIngredientes()
  {
    return listaIngredientesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getListaIngredientes_Ascii()
  {
    return (EAttribute)listaIngredientesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getListaIngredientes_Tipo()
  {
    return (EReference)listaIngredientesEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getListaIngredientes_Name()
  {
    return (EAttribute)listaIngredientesEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTipoVariable()
  {
    return tipoVariableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTipoVariable_INT()
  {
    return (EAttribute)tipoVariableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTipoVariable_String()
  {
    return (EAttribute)tipoVariableEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CocinitaFactory getCocinitaFactory()
  {
    return (CocinitaFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    cocinaEClass = createEClass(COCINA);
    createEAttribute(cocinaEClass, COCINA__NAME);
    createEReference(cocinaEClass, COCINA__INGREDIENTE);

    listaIngredientesEClass = createEClass(LISTA_INGREDIENTES);
    createEAttribute(listaIngredientesEClass, LISTA_INGREDIENTES__ASCII);
    createEReference(listaIngredientesEClass, LISTA_INGREDIENTES__TIPO);
    createEAttribute(listaIngredientesEClass, LISTA_INGREDIENTES__NAME);

    tipoVariableEClass = createEClass(TIPO_VARIABLE);
    createEAttribute(tipoVariableEClass, TIPO_VARIABLE__INT);
    createEAttribute(tipoVariableEClass, TIPO_VARIABLE__STRING);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(cocinaEClass, Cocina.class, "Cocina", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCocina_Name(), ecorePackage.getEString(), "name", null, 0, 1, Cocina.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCocina_Ingrediente(), this.getListaIngredientes(), null, "Ingrediente", null, 0, -1, Cocina.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(listaIngredientesEClass, ListaIngredientes.class, "ListaIngredientes", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getListaIngredientes_Ascii(), ecorePackage.getEString(), "ascii", null, 0, 1, ListaIngredientes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getListaIngredientes_Tipo(), this.getTipoVariable(), null, "tipo", null, 0, 1, ListaIngredientes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getListaIngredientes_Name(), ecorePackage.getEString(), "name", null, 0, 1, ListaIngredientes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(tipoVariableEClass, TipoVariable.class, "TipoVariable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTipoVariable_INT(), ecorePackage.getEString(), "INT", null, 0, 1, TipoVariable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTipoVariable_String(), ecorePackage.getEString(), "String", null, 0, 1, TipoVariable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //CocinitaPackageImpl
