/**
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.cocinita.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import upb.edu.lp.cocinita.CocinitaPackage;
import upb.edu.lp.cocinita.ListaIngredientes;
import upb.edu.lp.cocinita.TipoVariable;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Lista Ingredientes</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link upb.edu.lp.cocinita.impl.ListaIngredientesImpl#getAscii <em>Ascii</em>}</li>
 *   <li>{@link upb.edu.lp.cocinita.impl.ListaIngredientesImpl#getTipo <em>Tipo</em>}</li>
 *   <li>{@link upb.edu.lp.cocinita.impl.ListaIngredientesImpl#getName <em>Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ListaIngredientesImpl extends MinimalEObjectImpl.Container implements ListaIngredientes
{
  /**
   * The default value of the '{@link #getAscii() <em>Ascii</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAscii()
   * @generated
   * @ordered
   */
  protected static final String ASCII_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAscii() <em>Ascii</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAscii()
   * @generated
   * @ordered
   */
  protected String ascii = ASCII_EDEFAULT;

  /**
   * The cached value of the '{@link #getTipo() <em>Tipo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipo()
   * @generated
   * @ordered
   */
  protected TipoVariable tipo;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ListaIngredientesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CocinitaPackage.Literals.LISTA_INGREDIENTES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAscii()
  {
    return ascii;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAscii(String newAscii)
  {
    String oldAscii = ascii;
    ascii = newAscii;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CocinitaPackage.LISTA_INGREDIENTES__ASCII, oldAscii, ascii));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TipoVariable getTipo()
  {
    return tipo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTipo(TipoVariable newTipo, NotificationChain msgs)
  {
    TipoVariable oldTipo = tipo;
    tipo = newTipo;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CocinitaPackage.LISTA_INGREDIENTES__TIPO, oldTipo, newTipo);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTipo(TipoVariable newTipo)
  {
    if (newTipo != tipo)
    {
      NotificationChain msgs = null;
      if (tipo != null)
        msgs = ((InternalEObject)tipo).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CocinitaPackage.LISTA_INGREDIENTES__TIPO, null, msgs);
      if (newTipo != null)
        msgs = ((InternalEObject)newTipo).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CocinitaPackage.LISTA_INGREDIENTES__TIPO, null, msgs);
      msgs = basicSetTipo(newTipo, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CocinitaPackage.LISTA_INGREDIENTES__TIPO, newTipo, newTipo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CocinitaPackage.LISTA_INGREDIENTES__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CocinitaPackage.LISTA_INGREDIENTES__TIPO:
        return basicSetTipo(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CocinitaPackage.LISTA_INGREDIENTES__ASCII:
        return getAscii();
      case CocinitaPackage.LISTA_INGREDIENTES__TIPO:
        return getTipo();
      case CocinitaPackage.LISTA_INGREDIENTES__NAME:
        return getName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CocinitaPackage.LISTA_INGREDIENTES__ASCII:
        setAscii((String)newValue);
        return;
      case CocinitaPackage.LISTA_INGREDIENTES__TIPO:
        setTipo((TipoVariable)newValue);
        return;
      case CocinitaPackage.LISTA_INGREDIENTES__NAME:
        setName((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CocinitaPackage.LISTA_INGREDIENTES__ASCII:
        setAscii(ASCII_EDEFAULT);
        return;
      case CocinitaPackage.LISTA_INGREDIENTES__TIPO:
        setTipo((TipoVariable)null);
        return;
      case CocinitaPackage.LISTA_INGREDIENTES__NAME:
        setName(NAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CocinitaPackage.LISTA_INGREDIENTES__ASCII:
        return ASCII_EDEFAULT == null ? ascii != null : !ASCII_EDEFAULT.equals(ascii);
      case CocinitaPackage.LISTA_INGREDIENTES__TIPO:
        return tipo != null;
      case CocinitaPackage.LISTA_INGREDIENTES__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (ascii: ");
    result.append(ascii);
    result.append(", name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ListaIngredientesImpl
