/*
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.ui.tests;

import com.google.inject.Injector;
import miniLengCom.ui.internal.MiniLengComActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MiniLengComUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MiniLengComActivator.getInstance().getInjector("upb.edu.lp.MiniLengCom");
	}

}
