/*
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.validation;

import org.eclipse.xtext.validation.Check;

import upb.edu.lp.miniLengCom.FunctionCall;
import upb.edu.lp.miniLengCom.MiniLengComPackage;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class MiniLengComValidator extends AbstractMiniLengComValidator {
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					MiniLengComPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
	@Check
	public void checkNumberOfArguments(FunctionCall f) {
		if (f.getArgs().size() != f.getFunction().getParams().size()) {
			error("Mal cantidad de argumentos", 
					MiniLengComPackage.Literals.FUNCTION_CALL__ARGS	);
		}
	}
	
}
