/*
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import upb.edu.lp.parser.antlr.internal.InternalCocinitaParser;
import upb.edu.lp.services.CocinitaGrammarAccess;

public class CocinitaParser extends AbstractAntlrParser {

	@Inject
	private CocinitaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCocinitaParser createParser(XtextTokenStream stream) {
		return new InternalCocinitaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Cocina";
	}

	public CocinitaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CocinitaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
