/*
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractCocinitaValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(upb.edu.lp.cocinita.CocinitaPackage.eINSTANCE);
		return result;
	}
}
