/*
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.ui;

import cocinita.ui.internal.CocinitaActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CocinitaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(CocinitaActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		CocinitaActivator activator = CocinitaActivator.getInstance();
		return activator != null ? activator.getInjector(CocinitaActivator.UPB_EDU_LP_COCINITA) : null;
	}

}
