/*
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class MiniLengComProposalProvider extends AbstractMiniLengComProposalProvider {
}
