/*
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class CocinitaGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class CocinaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.edu.lp.Cocinita.Cocina");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRECIPEKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cIngredientesKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cIngredienteAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cIngredienteListaIngredientesParserRuleCall_3_0 = (RuleCall)cIngredienteAssignment_3.eContents().get(0);
		private final Keyword cProcedimientoKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Cocina:
		//    '[RECIPE]' name = ID
		//    'Ingredientes:'
		//    Ingrediente += ListaIngredientes*
		//    'Procedimiento:'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'[RECIPE]' name = ID
		//'Ingredientes:'
		//Ingrediente += ListaIngredientes*
		//'Procedimiento:'
		public Group getGroup() { return cGroup; }
		
		//'[RECIPE]'
		public Keyword getRECIPEKeyword_0() { return cRECIPEKeyword_0; }
		
		//name = ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'Ingredientes:'
		public Keyword getIngredientesKeyword_2() { return cIngredientesKeyword_2; }
		
		//Ingrediente += ListaIngredientes*
		public Assignment getIngredienteAssignment_3() { return cIngredienteAssignment_3; }
		
		//ListaIngredientes
		public RuleCall getIngredienteListaIngredientesParserRuleCall_3_0() { return cIngredienteListaIngredientesParserRuleCall_3_0; }
		
		//'Procedimiento:'
		public Keyword getProcedimientoKeyword_4() { return cProcedimientoKeyword_4; }
	}
	public class ListaIngredientesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.edu.lp.Cocinita.ListaIngredientes");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cASCIITerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cTipoAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTipoTipoVariableParserRuleCall_1_0 = (RuleCall)cTipoAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//ListaIngredientes:
		//    ASCII tipo=TipoVariable name=ID
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//ASCII tipo=TipoVariable name=ID
		public Group getGroup() { return cGroup; }
		
		//ASCII
		public RuleCall getASCIITerminalRuleCall_0() { return cASCIITerminalRuleCall_0; }
		
		//tipo=TipoVariable
		public Assignment getTipoAssignment_1() { return cTipoAssignment_1; }
		
		//TipoVariable
		public RuleCall getTipoTipoVariableParserRuleCall_1_0() { return cTipoTipoVariableParserRuleCall_1_0; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
	}
	public class TipoVariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.edu.lp.Cocinita.TipoVariable");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cINTAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final Keyword cINTOKeyword_0_0 = (Keyword)cINTAssignment_0.eContents().get(0);
		private final Assignment cStringAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final Keyword cStringCUKeyword_1_0 = (Keyword)cStringAssignment_1.eContents().get(0);
		private final Assignment cDoubleAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final Keyword cDoubleOKeyword_2_0 = (Keyword)cDoubleAssignment_2.eContents().get(0);
		
		//TipoVariable:
		//    INT ='[-o]' | String='[cU]' | Double='[-O]'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//INT ='[-o]' | String='[cU]' | Double='[-O]'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//INT ='[-o]'
		public Assignment getINTAssignment_0() { return cINTAssignment_0; }
		
		//'[-o]'
		public Keyword getINTOKeyword_0_0() { return cINTOKeyword_0_0; }
		
		//String='[cU]'
		public Assignment getStringAssignment_1() { return cStringAssignment_1; }
		
		//'[cU]'
		public Keyword getStringCUKeyword_1_0() { return cStringCUKeyword_1_0; }
		
		//Double='[-O]'
		public Assignment getDoubleAssignment_2() { return cDoubleAssignment_2; }
		
		//'[-O]'
		public Keyword getDoubleOKeyword_2_0() { return cDoubleOKeyword_2_0; }
	}
	
	
	private final CocinaElements pCocina;
	private final ListaIngredientesElements pListaIngredientes;
	private final TipoVariableElements pTipoVariable;
	private final TerminalRule tASCII;
	private final TerminalRule tID;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public CocinitaGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pCocina = new CocinaElements();
		this.pListaIngredientes = new ListaIngredientesElements();
		this.pTipoVariable = new TipoVariableElements();
		this.tASCII = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "upb.edu.lp.Cocinita.ASCII");
		this.tID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "upb.edu.lp.Cocinita.ID");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("upb.edu.lp.Cocinita".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Cocina:
	//    '[RECIPE]' name = ID
	//    'Ingredientes:'
	//    Ingrediente += ListaIngredientes*
	//    'Procedimiento:'
	//;
	public CocinaElements getCocinaAccess() {
		return pCocina;
	}
	
	public ParserRule getCocinaRule() {
		return getCocinaAccess().getRule();
	}
	
	//ListaIngredientes:
	//    ASCII tipo=TipoVariable name=ID
	//;
	public ListaIngredientesElements getListaIngredientesAccess() {
		return pListaIngredientes;
	}
	
	public ParserRule getListaIngredientesRule() {
		return getListaIngredientesAccess().getRule();
	}
	
	//TipoVariable:
	//    INT ='[-o]' | String='[cU]' | Double='[-O]'
	//;
	public TipoVariableElements getTipoVariableAccess() {
		return pTipoVariable;
	}
	
	public ParserRule getTipoVariableRule() {
		return getTipoVariableAccess().getRule();
	}
	
	//terminal ASCII:
	//    ('0'..'9')+
	//;
	public TerminalRule getASCIIRule() {
		return tASCII;
	}
	
	//terminal ID:
	//    ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '0'..'9' | '_')*
	//;
	public TerminalRule getIDRule() {
		return tID;
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
