/*
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.ui.tests;

import cocinita.ui.internal.CocinitaActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class CocinitaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CocinitaActivator.getInstance().getInjector("upb.edu.lp.Cocinita");
	}

}
