/*
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCocinitaScopeProvider extends DelegatingScopeProvider {
}
