/*
 * generated by Xtext 2.35.0
 */
package upb.edu.lp.validation;

import org.eclipse.xtext.validation.Check;

import upb.edu.lp.cocinita.CocinitaPackage;
import upb.edu.lp.cocinita.ListaIngredientes;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class CocinitaValidator extends AbstractCocinitaValidator {
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					CocinitaPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	@Check
    public void checkASCII(ListaIngredientes ingrediente) {
		if (ingrediente.getAscii() != null) {
            try {
                int asciiValue = Integer.parseInt(ingrediente.getAscii());
                if (asciiValue < 33 || asciiValue > 126) {
                    error("ASCII value must be between 33 and 126", 
                          CocinitaPackage.Literals.LISTA_INGREDIENTES__ASCII, 
                          "invalid-ascii-value");
                }
            } catch (NumberFormatException e) {
                error("Invalid ASCII value", 
                      CocinitaPackage.Literals.LISTA_INGREDIENTES__ASCII, 
                      "invalid-ascii-value");
            }
        }
    }
	
	
}
